
export const categoryList = [
  {
    id: "3",
    name: "Electronics",
    shortName: "Electronics",
    routeName: "Electronics",
    domain: "ONDC:RET14",
  },
  {
    id: "9",
    name: "Appliances",
    shortName: "Appliances",
    routeName: "Appliances",
    domain: "ONDC:RET15",
  },
   {
    id: "10",
    name: "Home",
    shortName: "Home",
    routeName: "Home",
    domain: "ONDC:RET16", // Assuming domain for Home
  },
  {
      id: "12", // Arbitrary ID
      name: "Personal Care",
      shortName: "Personal Care",
      routeName: "Personal Care",
      domain: "ONDC:RET13"
  }
];

export const PRODUCT_SUBCATEGORY = {
  Electronics: [
     { value: "3D Glasses", icon: "glasses", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "3D Modulator", icon: "cubes", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Adapter", icon: "plug-circle-bolt", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Audio Accessories", icon: "sliders", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Batteries", icon: "battery-three-quarters", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Biometrics", icon: "fingerprint", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Cable", icon: "link", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Camcorder", icon: "video", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Camera", icon: "camera", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Camera Accessories", icon: "camera-retro", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Camera Bag", icon: "briefcase", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Camera Lens", icon: "eye", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Charger", icon: "plug", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Computer Accessories", icon: "headgear", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Computer Component", icon: "microchip", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Computer Software", icon: "compact-disc", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Cooling Pad", icon: "bore-hole", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Desktop", icon: "desktop", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Digital Photo Frame", icon: "image", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Docking Station", icon: "envelopes-bulk", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Earphone", icon: "ear-listen", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Ebook Reader", icon: "book-open-reader", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Extension Cord", icon: "grip-lines", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Gaming Accessories", icon: "headset", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Gaming Chair", icon: "chair", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Gaming Console", icon: "ghost", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Gaming Controller", icon: "gamepad", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Headset", icon: "headphones-simple", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Home Alarm", icon: "bell", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Home Audio", icon: "volume-high", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Home Automation", icon: "house-signal", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Home Safe", icon: "vault", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Home Theatre Projector", icon: "clapperboard", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Intercom", icon: "phone-volume", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Keyboard", icon: "keyboard", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Keyboard Guard", icon: "mask", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Laptop", icon: "laptop", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Laptop Bag", icon: "bag-shopping", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Laptop Skin", icon: "palette", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Laptop Stand", icon: "laptop-code", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Memory Card", icon: "sd-card", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Microphone", icon: "microphone", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Mobile Cover", icon: "mobile-retro", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Mobile Mount", icon: "magnet", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Mobile Phone", icon: "mobile-screen-button", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Mobile Screen Guard", icon: "shield-halved", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Mobile Skin Sticker", icon: "note-sticky", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Monitor", icon: "display", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Mouse", icon: "mouse", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Mousepad", icon: "border-all", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Networking Device", icon: "router", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Pen Drive", icon: "hard-drive", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Photo Printer", icon: "images", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Power Bank", icon: "battery-full", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Printer", icon: "print", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Printer Accessories", icon: "droplet-degree", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Projector", icon: "video-slash", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Projector Accessories", icon: "plug-circle-xmark", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Projector Mount", icon: "up-down-left-right", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Projector Screen", icon: "chalkboard", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Remote", icon: "toggle-on", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Screen Protector", icon: "window-maximize", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Selfie Stick", icon: "arrows-up-to-line", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Sensor", icon: "satellite-dish", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Set Top Box", icon: "box-open", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Smart Band", icon: "circle-nodes", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Smart Glasses", icon: "eye-low-vision", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Smart Lighting", icon: "lightbulb", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Smart Ring", icon: "ring", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Smart Switch", icon: "toggle-off", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Smart TV", icon: "tv", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Smart Watch", icon: "watch-apple", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Speaker", icon: "bullhorn", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Standard TV", icon: "rectangle-list", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Storage Drive", icon: "database", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Streaming Device", icon: "play", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Tablet", icon: "tablet-screen-button", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Tablet Accessories", icon: "pen-nib", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Tripod", icon: "tower-broadcast", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "True Wireless Stereo (TWS)", icon: "headphones", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "TV Accessories", icon: "cable-car", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "TV Mount", icon: "frame", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "TV Part", icon: "puzzle-piece", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "TV Remote", icon: "rss", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "TV Stand", icon: "window-minimize", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "UPS", icon: "plug-circle-check", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Vehicle Audio", icon: "car", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Video Games", icon: "vr-cardboard", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Video Player", icon: "film", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Video Player Accessories", icon: "file-video", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Virtual Reality Headset", icon: "head-side-mask", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Watch Strap Band", icon: "grip-lines-vertical", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
     { value: "Wearable Accessories", icon: "person-running", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
  ],
  Appliances: [
       { value: "Air Cleaner Accessories", icon: "gears", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Air Conditioner", icon: "snowflake", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Air Conditioner Accessories", icon: "screwdriver-wrench", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Air Cooler", icon: "fan", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Air Heater", icon: "fire-flame-simple", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Air Purifier", icon: "wind", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Battery tray", icon: "table-cells-large", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Beverage Maker", icon: "glass-water", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Blender", icon: "blender", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Coffee Grinder", icon: "mortar-pestle", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Coffee Maker", icon: "mug-hot", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Cooking Appliance Accessories", icon: "kitchen-set", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Dehumidifier", icon: "droplet-slash", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Dishwasher", icon: "soap", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Dishwasher Accessories", icon: "circle-nodes", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Electric Air Fryer", icon: "drumstick-bite", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Electric Brush", icon: "broom", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Electric Chimney", icon: "smog", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Electric Cooker", icon: "bowl-rice", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Electric Iron", icon: "shirt", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Electric Kettle", icon: "mug-saucer", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Electric Sewing Machine", icon: "scissors", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Food Processor", icon: "robot", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Food Processor Accessories", icon: "blade", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Freezer", icon: "icicles", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Heater Cables", icon: "bezier-curve", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Humidifier", icon: "droplet", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Induction Cooktop", icon: "circle-dot", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Inverter", icon: "bolt-lightning", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Inverter Batteries", icon: "car-battery", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Juicer", icon: "lemon", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Kitchen Accessories", icon: "utensils", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Microwave Oven", icon: "wave-square", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Mixer Grinder", icon: "hurricane", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "OTG", icon: "temperature-high", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Pasta Maker", icon: "wheat-awn", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Refrigerator", icon: "box", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Refrigerator Accessories", icon: "egg", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Roti Maker", icon: "circle-pause", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Sandwich Maker", icon: "equals", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Toaster", icon: "bread-slice", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Vacuum Cleaner", icon: "broom-ball", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Vacuum Cleaner Parts and Accessories", icon: "toolbox", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Voltage Stabilizer", icon: "gauge-high", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Washing Machine", icon: "socks", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Washing Machine Accessories", icon: "bucket", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Cooler", icon: "temperature-arrow-down", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Cooler Accessories", icon: "vial", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Dispenser", icon: "faucet", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Heater", icon: "shower", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Purifier", icon: "hand-holding-droplet", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Purifier Accessories", icon: "wrench", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Purifier Candle", icon: "prescription-bottle", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Purifier Filter", icon: "filter", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Purifier Pipe", icon: "lines-leaning", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Water Purifier Service Kit", icon: "medkit", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
       { value: "Wet Grinder", icon: "recycle", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
  ],
  Home: [
    { value: "Car and Shoe Care", icon: "shoe-prints", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Closet/Laundry/Shoe Organization", icon: "box-archive", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Cookware", icon: "pan-frying", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Disposables and Garbage Bags", icon: "recycle", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Electricals", icon: "bolt", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Flowers", icon: "flower-tulip", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Fresheners and Repellents", icon: "spray-can", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Furniture", icon: "couch", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Garden & Outdoor", icon: "tree", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Hardware, Tools and Home Safety", icon: "hammer", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Home Decor", icon: "icons", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Home Furnishing - Bedding and Linen", icon: "bed", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Kitchen Storage and Containers", icon: "boxes-stacked", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Kitchen Tools", icon: "utensils", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Mops, Brushes and Scrubs", icon: "broom-ball", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Paint and Wallpapers", icon: "paint-roller", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Party and Festive Needs", icon: "champagne-glasses", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Pooja Needs", icon: "om", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Serveware", icon: "plate-wheat", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Sports and Fitness Equipment", icon: "dumbbell", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Stationery", icon: "pen-fancy", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Toys and Games", icon: "puzzle-piece", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
    { value: "Tracker Devices", icon: "location-crosshairs", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
  ],
  "Personal Care": [
      { value: "Bathroom and Kitchen fixtures", icon: "sink", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
      { value: "Bins and Bathroom", icon: "trash-can", protocolKey: "@ondc/org/statutory_reqs_packaged_commodities" },
  ]
};
